#!/usr/bin/env bash

source ${CLI_PATH}/config/colors

cd $EDEF_PATH

set -e
if [ "$#" -lt 1 ]; then
  echo -e "${RED}Please insert at least one or more arguments${NC} ${CYAN}[-frontend, -backend, -mongo]${NC}"
  exit
else
  echo -e "\c"
fi

for arg
do
    case "$arg" in
        -mongo)
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml up mongo
            ;;
        -frontend)
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml up frontend
            ;;
        -backend)
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml up backend
            ;;
        *)
            echo -e "${RED}Unknown argument${NC}"
            exit 1
            ;;
     esac
done

echo -e "${GREEN}All done, services started.${NC}"
