#!/usr/bin/env bash

cd $EDEF_PATH

if [[ $1 = '--help' ]] || [[ $1 = '-h' ]]; then
  printf "issue-start - help:
  Usage:
  edef-issue-start [ISSUE_NUMBER] \n
  (start the issue [ISSUE_NUMBER]):
  Example:
  edef-issue-start 100 \n"
  exit 0;
fi

LAST_BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
LAST_ISSUE=${LAST_BRANCH/issue#/}
LAST_MODIF=$(git log origin/master..HEAD)

# Branch Master
git checkout master
git fetch origin
git pull origin master

# Branch Issue
if [[ -n $(git branch | grep issue#$1) ]]; then
	git checkout -b issue#$1
	git pull origin master
	git push --set-upstream origin issue#$1
else
	git checkout -b issue#$1
	git pull origin master
	git push --set-upstream origin issue#$1
fi

git branch -D $LAST_BRANCH
git push origin --delete $LAST_BRANCH
git pull origin master

cd $EDEF_PATH/backend

echo "Everything done, now on Branch: issue#$1"
