#!/usr/bin/env bash

cd $EDEF_PATH

if [[ $1 == '--help' || $1 == '-h' ]]; then
  printf "edef-app-deploy - help: \n
  Usage:
  edef-app-deploy [AMBIENCE]\n"
  exit 0;
fi

echo "Starting Deploy..."

if [[ $1 == '--homolog' ]]; then
  $CLI_PATH/edef-slack-notify --homolog "Starting Homolog Deploy..."
  git pull origin master

  #Backend
  cd $EDEF_PATH/backend
  composer install --no-scripts --no-dev --no-interaction --prefer-dist

  php artisan config:clear  
  php artisan cache:clear

  php artisan migrate --force
  
  composer dump-autoload

  #Frontend
  cd $EDEF_PATH/frontend
  yarn install
  sudo rm -r build/
  yarn build 

  $CLI_PATH/edef-slack-notify --homolog "Homolog Deploy Done!"
  echo 'Deploy done.'
elif [[ $1 == '--production' ]]; then
  #TODO
  echo 'Deploy done.'
else
  echo 'Ambience not selected.'
fi 
