#!/usr/bin/env bash

CREDENTIALS_FILE=$EDEF_PATH/devops/.edef-github-credentials

set_credentials() {
  echo 'Type your Github user:'
  read user
  echo 'Type your Github password or your personal access token (https://github.com/settings/tokens/new):'
  read -s pass

  echo $user >> $CREDENTIALS_FILE
  echo $pass >> $CREDENTIALS_FILE
}

get_user() {
  head -n1 $CREDENTIALS_FILE | tr -d "[:space:]"
}

get_pass() {
  tail -n1 $CREDENTIALS_FILE | tr -d "[:space:]"
}

if [ $1 == '--config' ]; then
  set_credentials
elif [ $1 == '--user' ]; then
  echo $(get_user)
elif [ $1 == '--pass' ]; then
  echo $(get_pass)
elif [ $1 == '--login' ]; then
  echo "$(get_user):$(get_pass)"
else
  echo "Invalid argument $1"
  exit 1
fi
