#!/usr/bin/env bash

source ${CLI_PATH}config/colors

cd $EDEF_PATH/backend

echo -e "${PURPLE}Installing dependencies${NC} on backend..."
composer install

cd $EDEF_PATH/frontend

echo -e "${PURPLE}Installing dependencies${NC} on frontend..."
yarn install

echo -e "${GREEN}All done, dependencies installed.${NC}"
