#!/usr/bin/env bash

TIMESTAMP=$(date +%F_%H%M)
BACKUP_NAME="edef_pr-$TIMESTAMP"

mysqldump --user root $MYSQL_DATABASE > $BACKUP_NAME

mkdir -p $BACKUPS_DIR
mv $BACKUP_NAME $BACKUPS_DIR/$BACKUP_NAME
cd $BACKUPS_DIR
tar -zcvf $BACKUP_NAME.tgz $BACKUP_NAME
rm -rf $BACKUP_NAME

# note: make sure the dir is setup correctly for the bitbucket repository
#git add $BACKUP_NAME.tgz
#git commit -m "Daily backup"
#git push -u origin master
