#!/usr/bin/env bash

source ${CLI_PATH}config/colors

echo -e "${PURPLE}Applying http_proxy${NC} for yarn..."
yarn config set proxy http://proxy:8080
echo -e "${PURPLE}Applying https_proxy${NC} for yarn..."
yarn config set https-proxy http://proxy:8080

echo -e "${PURPLE}Applying http_proxy${NC} for GIT..."
git config --global http.proxy http://proxy:8080
echo -e "${PURPLE}Applying https_proxy${NC} for GIT..."
git config --global https.proxy http://proxy:8080

echo -e "${PURPLE}Applying http_proxy${NC} for Linux terminal..."
export http_proxy="http://proxy:8080"
echo -e "${PURPLE}Applying https_proxy${NC} for Linux terminal..."
export https_proxy="http://proxy:8080"
echo -e "${GREEN}All done, proxies applied.${NC}"
