#!/usr/bin/env bash

cd $EDEF_PATH

BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
ISSUE=${BRANCH/issue#/}

echo 'GitHub login:'
read USER
echo 'GitHub password or token (https://github.com/settings/tokens/new):'
read -s PASS

open_pull_request() {
	local head="C3DSU:$BRANCH"
	local base="master"
	local title="$BRANCH"
	local body="fixed #$ISSUE"

	LOGIN="$USER:$PASS"

	json="{\"head\":\"$head\",\"base\":\"$base\",\"title\":\"$title\",\"body\":\"$body\"}"
	echo $(curl -s -X POST -u $LOGIN -d "$json" $GITHUB_REPOSITORY/pulls)
}

get_pull_request_number() {
	read x
	echo $x | grep \"number\" | grep -oP '(?<="number": ).*(?=, "state")'
}

echo 'Creating Pull Request in the GitHub repository...'
pr=$(open_pull_request | get_pull_request_number)

if [[ -z $pr ]]; then
    echo 'Error: Pull Request could not be processed'
    exit 1
else
    echo "Sucess: https://github.com/C3DSU/e-DefPR/pull/$pr/files"
fi
