#!/usr/bin/env bash

export PROJECT_ROOT=$EDEF_PATH/backend
export CLI_PATH=$EDEF_PATH/devops/
export GITHUB_REPOSITORY='https://api.github.com/repos/C3DSU/e-DefPR'
export PATH="$EDEF_PATH/devops:$PATH"
export MONGO_DATABASE='e-defpr'
export MONGO_HOST="127.0.0.1"
export MONGO_PORT="27017"
export BACKUPS_DIR="$EDEF_PATH/devops/backups"
